server:
  port: 8888
spring:
  mail:
    host: smtp.163.com
    username: lyxaccount@163.com
    password:
    port: 465
    from: lyxaccount@163.com
    default-encoding: utf-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: localhost
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 50
        max-wait: 3000ms
        max-idle: 20
        min-idle: 5
    timeout: 5000ms


  application:
    name: allDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alldemo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid:
      keysecret:
      bucketname: l-y-x-bucket

mybatis-plus:
  mapper-locations: classpath*:com/example/interfacedemo/mapperxml/*/*.xml,classpath*:com/example/interfacedemo/mapperxml/*.xml
  #所映射的实体类的包名
  type-aliases-package: com.example.interfacedemo.entity
#  mapper-locations: classpath*:com/example/interfacedemo/**/*.xml,classpath*:com/example/interfacedemo/*/*.xml
# 错误的配置如下，正确的应该至少包含com/example/**
#  mapper-locations: classpath*:com/**/*.xml,classpath*:com/*/*.xml
logging:
  level:
    com.example.interfacedemo.mapper: debug

#jwt设置
# JWT存储的请求头
jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer




